store projection error objects
patchlevel/event-sourcing pull request #436
Opened 2023-12-13 13:36 UTC by DavidBadura

* fix #397

2023-12-13 14:36 UTC, DanielBadura requested changes

2023-12-13 14:36 UTC, DanielBadura commented on src/Console/Command/ProjectionStatusCommand.php
> +            dump($errorObject);
should be removed

2023-12-13 14:43 UTC, DavidBadura commented on src/Console/Command/ProjectionStatusCommand.php
> +            dump($errorObject);
I want to dump the exception

2023-12-14 09:13 UTC, DavidBadura commented on src/Console/Command/ProjectionStatusCommand.php
> +            dump($errorObject);
replaced

2023-12-14 12:57 UTC, DanielBadura approved these changes

2023-12-14 12:59 UTC, merged