Lookup
patchlevel/event-sourcing pull request #659
Opened 2024-12-17 08:49 UTC by DavidBadura

This allows you to look at the current event stream in your subscription.
To look up information that is only relevant now. It also ensures that you cannot see into the future.

```php
#[Subscribe(AuctionClosed::class)]
public function onAuctionClosed(AuctionClosed $event, Lookup $lookup): void
{
    $messages = $lookup->lookBack(
      Sold::class,
      AuctionPublished::class
    );
    
    $state = (new Reducer())
        ->initState(['description' => null, 'price' => null])
        ->match([
            Sold::class => static function (Message $message): array {
                return ['price' => $message->event()->price];
            },
            AuctionPublished::class => static function (Message $message): array {
                return ['description' => $message->event()->description];
            },
        ])
        ->reduce($messages);
        
    $this->connection->insert('expired_auctions', $state);
}
```

The API of the Lookup class is not finished yet. I am thinking about how to build the API for it to filter by aggregateId, etc.

2025-01-13 15:37 UTC, DanielBadura requested changes

2025-01-13 15:37 UTC, DanielBadura commented on src/Serializer/DefaultEventSerializer.php
> +    public function eventRegistry(): EventRegistry
I'm not in favor of adding this method, just to have it easier in the tests. The `createFromPaths` is there to ease the creation and usage of this class by creating the object with reasonable default dependencies but this makes accessing the internal dependencies harder. Adding then methods to access these deps is not the solution imho, the solution should be to create this class manually then and not relying on `createFromPaths`.

The bare minimum should be marking this internal, as no user should rely on this.

2025-01-13 15:37 UTC, DanielBadura commented on src/Message/Reducer.php
> +        if ($messages === null) {
Why are we changing the API how to provide the messages? I did not see any usage here for the extra `Reducer::messages` method. This seems to just complicate things, no?


In this example, `messagesA` is unused, this could lead to confusion.
```php
$reducer = (new Reducer)->messages($messagesA);

$reducers->reduce($messagesB);
```

2025-01-13 15:37 UTC, DanielBadura commented on src/Subscription/Lookup/Lookup.php
> +                new ToIndexCriterion($this->currentMessage->header(IndexHeader::class)->index),
this could already happen in the constructor, so then it never happens this will be missed, no?

2025-01-13 15:37 UTC, DanielBadura commented on src/Subscription/Lookup/Lookup.php
> +        $this->criteria = new Criteria();
```suggestion
        $this->criteria = (new Criteria())->add(new ToIndexCriterion($this->currentMessage->header(IndexHeader::class)->index));
```

2025-01-14 14:11 UTC, DavidBadura commented on src/Message/Reducer.php
> +        if ($messages === null) {
reverted

2025-01-14 15:31 UTC, DanielBadura approved these changes

2025-01-14 15:32 UTC, merged